# Header
menu:
  ä¸»é¡µ: /
  æ‰€æœ‰æ–‡ç« : /archives
  #éšç¬”: /tags/éšç¬”

# SubNav
subnav:
  github: https://github.com/zhipingyang
  weibo: http://weibo.com/p/1006062608078012/home
  mail: xcodeyang@gmail.com
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# æ˜¯å¦å¼€å¯åŠ¨ç”»æ•ˆæœ
animate: true

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#ä½ çš„å¤´åƒurl
avatar: 'https://avatars3.githubusercontent.com/u/9360037'
#æ˜¯å¦å¼€å¯åˆ†äº«
share: true
#æ˜¯å¦å¼€å¯å¤šè¯´è¯„è®ºï¼Œå¡«å†™ä½ åœ¨å¤šè¯´ç”³è¯·çš„é¡¹ç›®åç§° duoshuo: duoshuo-key
#è‹¥ä½¿ç”¨disqusï¼Œè¯·åœ¨åšå®¢configæ–‡ä»¶ä¸­å¡«å†™disqus_shortnameï¼Œå¹¶å…³é—­å¤šè¯´è¯„è®º
duoshuo: true
#æ˜¯å¦å¼€å¯äº‘æ ‡ç­¾
tagcloud: true

#æ˜¯å¦å¼€å¯å‹æƒ…é“¾æ¥
#ä¸å¼€å¯â€”â€”
#friends: false
#å¼€å¯â€”â€”
friends:
  tomatopeter's blog': http://www.tomatopeter.com/
  ming.z's blog: http://ioi.im/

#æ˜¯å¦å¼€å¯â€œå…³äºæˆ‘â€ã€‚
#ä¸å¼€å¯â€”â€”
#aboutme: false
#å¼€å¯â€”â€”
aboutme: æ›¾ç»å¾ˆå¤šäººè¯´æˆ‘é€—é€¼ï¼Œæˆ‘ä¸è¿™ä¹ˆè®¤ä¸ºï¼Œæˆ‘è§‰å¾—è‡ªå·±æ˜¯ä¸€ä¸ªååˆ†æ­£ç»çš„ä»£ç æ¬è¿å·¥ï¼Œç«‹å¿—äº30å²å‰ç»“å©šğŸ˜‚